plugins:
  - name: "smb"
    path: "plugins/smb/build/smb"
  - name: "http"
    path: "plugins/http/build/http"
  - name: "tcp"
    path: "plugins/tcp/build/tcp"


crystal-palace:
  lib: "/path/to/crystalpalace.jar"
  pavilion: "./pavilion"
